name: ​🐞 Bug
description: Report an issue to help us improve the project.
title: "[BUG] <write a small description here>"
labels: ["bug", "goal: fix", "priority: medium"]
body:
  - type: textarea
    attributes:
      label: Description
      description: A brief description of the issue or bug you are facing, also include what you tried and what didn't work.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Screenshots
      description: Please add screenshots if applicable
    validations:
      required: false
  - type: textarea
    attributes:
      label: Any additional information?
      description: Any additional information or Is there anything we should know about this bug?
    validations:
      required: false
  - type: dropdown
    attributes:
      
      - label: "I have checked the existing [issues](https://github.com/Curious-Ecosystem/Curious-Connect/issues)."
          required: true

        - label: "I have read the [Contributing Guidelines](https://github.com/Curious-Ecosystem/Curious-Connect/blob/main/CONTRIBUTING.md)"
          required: true

        - label: "I have read the [Code Of Conduct](https://github.com/Curious-Ecosystem/Curious-Connect/blob/main/CODE_OF_CONDUCT.md)"
          required: true
        - label: "I joined onboarding group for knowledge flow and direct conversation and support from admins  [Curious Developers Community - Curious Connect](https://chat.whatsapp.com/FR0sVnpsSvL4J4l56vLdBN)"
          required: true

        - label: "The changes don't break the code and don't introduce new functionality."
          required: true

        - label: "Please attach the screenshots and video of the development work once it is done "
          required: true
        - label: "Contributions more than 3 will be awarded a certificate of appreciation from curious ecosystem  "
          required: true
        - label: "please mail to ([admin@curiousdevelopers.in](mailto:admin@curiousdevelopers.in)) for claiming certificate and please attach your issue numbers "
          required: true
        - label: "I am willing to work on this issue (optional)."
          required: false
