name: Refactor Code 🔧
description: Use this label for code refactoring tasks.
title: "[Refactor] <write what you want to add>"
labels: ["goal: refactor", "priority: medium"]
body:
  - type: input
    attributes:
      label: File Name
      description: "Enter the file that you want to refactor in the codebase."
      placeholder: "For example - component/Cards/Card.tsx"
    validations:
      required: true
  - type: textarea
    id: refactor_description
    attributes:
      label: "Reason for Refactoring the Code"
      description: "Describe what improvements can be made in the codebase without introducing breaking changes."
    validations:
      required: true
  - type: checkboxes
    id: no-duplicate-issues
  Instructions: 
  Stay you can start working on it by taking latest pull from main branch
  - [ ] Please read the contributors guidelines [Contributing Guidelines](https://github.com/Curious-Ecosystem/Curious-Connect/blob/main/CONTRIBUTING.md).
  - [ ] Please follow the code of conduct [Code Of Conduct](https://github.com/Curious-Ecosystem/Curious-Connect/blob/main/CODE_OF_CONDUCT.md)
  - [ ] Don't Forget to join onboarding group for knowledge flow and direct conversation and support from admins
  - [ ] **Link** [Curious Developers Community - Curious Connect](https://chat.whatsapp.com/FR0sVnpsSvL4J4l56vLdBN)
  - [ ] Please attach the screenshots and video of the development work once it is done 
  - [ ] Contributions more than 3 will be awarded a certificate of appreciation from curious ecosystem 
  - [ ] please mail to ([admin@curiousdevelopers.in](mailto:admin@curiousdevelopers.in)) for claiming certificate and please attach your issue number

  Respect Co Developers And Please Reach-out to admins if any issues
  
    attributes:
      label: "Checklist"
      options:
        - label: "I have checked the existing [issues](https://github.com/Curious-Ecosystem/Curious-Connect/issues)."
          required: true

        - label: "I have read the [Contributing Guidelines](https://github.com/Curious-Ecosystem/Curious-Connect/blob/main/CONTRIBUTING.md)"
          required: true

        - label: "I have read the [Code Of Conduct](https://github.com/Curious-Ecosystem/Curious-Connect/blob/main/CODE_OF_CONDUCT.md)"
          required: true
        - label: "I joined onboarding group for knowledge flow and direct conversation and support from admins  [Curious Developers Community - Curious Connect](https://chat.whatsapp.com/FR0sVnpsSvL4J4l56vLdBN)"
          required: true

        - label: "The changes don't break the code and don't introduce new functionality."
          required: true

        - label: "I am willing to work on this issue (optional)."
          required: false

        - label: "I am willing to work on this issue (optional)."
          required: false
